package nexa.framework.runtime.domain.workspace.compiler;

public enum BytecodeOpcode {
    LOAD_CONSTANT,
    LOAD_LOCAL,
    STORE_LOCAL,
    LOAD_SELF,
    LOAD_TAG,
    STORE_TAG,
    ADD_INT8, ADD_INT16, ADD_INT32, ADD_INT64,
    ADD_UINT8, ADD_UINT16, ADD_UINT32, ADD_UINT64,
    ADD_FLOAT32, ADD_FLOAT64,
    SUB_INT32, SUB_INT64, SUB_FLOAT32, SUB_FLOAT64,
    MUL_INT32, MUL_INT64, MUL_FLOAT32, MUL_FLOAT64,
    DIV_INT32, DIV_INT64, DIV_FLOAT32, DIV_FLOAT64,
    COMPARE,
    JUMP,
    JUMP_IF_FALSE,
    GET_PROPERTY,
    SET_PROPERTY,
    ARRAY_GET,
    ARRAY_SET,
    CALL_HOST,
    RETURN
}
