/*
 * This source file was generated by the Gradle 'init' task
 */
package nexa.framework;

import nexa.framework.runtime.api.OutputConsumer;
import nexa.framework.runtime.api.RuntimeConfiguration;
import nexa.framework.runtime.api.RuntimeEngine;
import nexa.framework.runtime.domain.workspace.model.WorkspaceDefinition;
import nexa.framework.runtime.domain.execution.service.DefaultRuntimeEngine;
import nexa.framework.runtime.domain.workspace.service.WorkspaceJsonLoader;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.concurrent.CountDownLatch;

public class App {

    public static void main(String[] args) {
        info("Memuat file workspace JSON");
        String workspaceJson = loadWorkspaceJson();

        OutputConsumer outputConsumer = (context, nodeId, message) -> System.out.println(
                "[node=" + nodeId + "]" +
                        "[workspace=" + context.workspaceId() + "]" +
                        "[flow=" + context.flowId() + "]" +
                        "[execution=" + context.executionId() + "]" + "|" +
                        "[payload=" + message.values() + "]");

        RuntimeEngine runtime = new DefaultRuntimeEngine(
                RuntimeConfiguration.defaultConfiguration(),
                outputConsumer);

        info("Menyiapkan parser workspace");
        WorkspaceJsonLoader loader = new WorkspaceJsonLoader();
        CountDownLatch shutdownSignal = new CountDownLatch(1);

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            info("Sinyal shutdown diterima, menghentikan runtime");
            runtime.stopRuntime();
            shutdownSignal.countDown();
            info("Runtime berhenti dengan graceful shutdown");
        }, "nexa-shutdown-hook"));

        info("Parsing workspace JSON");
        WorkspaceDefinition workspaceDefinition = loader.fromJson(workspaceJson);

        info("Deploy workspace id=" + workspaceDefinition.id());
        runtime.deploy(workspaceDefinition);

        info("Menyalakan runtime");

        try {
            Thread.sleep(2000); // Delay untuk memastikan log deploy muncul sebelum log runtime aktif
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
        }

        runtime.startRuntime();
        info("Runtime aktif. Tekan Ctrl+C untuk menghentikan.");

        try {
            shutdownSignal.await();
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
        } finally {
            info("Final cleanup runtime");
            runtime.stopRuntime();
        }
    }

    private static String loadWorkspaceJson() {
        Path workspacePath = Paths.get("workspaces", "workspace-main.json");

        try {
            if (!Files.exists(workspacePath)) {
                throw new IllegalStateException(
                        "Workspace file not found: " + workspacePath.toAbsolutePath());
            }

            return Files.readString(workspacePath);

        } catch (IOException ex) {
            throw new IllegalStateException(
                    "Unable to load workspace file: " + workspacePath.toAbsolutePath(), ex);
        }
    }

    private static void info(String message) {
        System.out.println("[nexa][app] " + message);
    }

}
