package nexa.compiler.lang;

import java.util.*;
import static nexa.compiler.lang.NexaAst.*;

public final class NexaTypeChecker {
    public record Diagnostic(String message, SourceSpan span) {}
    private final Map<String,NexaType> types=new HashMap<>(); private final List<Diagnostic> errors=new ArrayList<>(); private final Deque<Map<String,NexaType>> scopes=new ArrayDeque<>();
    public NexaTypeChecker(){for(NexaType t:List.of(NexaType.BOOLEAN,NexaType.INT8,NexaType.INT16,NexaType.INT32,NexaType.INT64,NexaType.UINT8,NexaType.UINT16,NexaType.UINT32,NexaType.UINT64,NexaType.FLOAT32,NexaType.FLOAT64,NexaType.STRING,NexaType.OBJECT,NexaType.VOID))types.put(t.displayName(),t);}
    public List<Diagnostic> check(Program p){errors.clear();scopes.clear();scopes.push(new HashMap<>());for(Stmt s:p.statements())checkStmt(s);return List.copyOf(errors);}
    private void checkStmt(Stmt s){if(s instanceof TypeDecl d){if(types.containsKey(d.name()))err("Type already defined: "+d.name(),d.span());else types.put(d.name(),d.type());return;}if(s instanceof Let l){NexaType init=expr(l.init());requireAssignable(l.type(),init,l.span(),"initializer");define(l.name(),resolve(l.type()));return;}if(s instanceof Assign a){NexaType t=expr(a.target()),v=expr(a.value());if(!isLValue(a.target()))err("Assignment target is not writable",a.target().span());requireAssignable(t,v,a.span(),"assignment");return;}if(s instanceof Return r){expr(r.value());return;}if(s instanceof ExprStmt e){expr(e.expr());return;}if(s instanceof For f){NexaType it=expr(f.iterable());if(!(it instanceof NexaType.Array arr))err("'in' requires ARRAY<T>",f.iterable().span());else{requireAssignable(f.declaredType(),arr.element(),f.span(),"loop variable");scopes.push(new HashMap<>());define(f.name(),resolve(f.declaredType()));for(Stmt b:f.body())checkStmt(b);scopes.pop();}}}
    private NexaType expr(Expr e){if(e instanceof Literal l)return l.type();if(e instanceof Var v){NexaType t=lookup(v.name());if(t==null){err("Unknown variable: "+v.name(),v.span());return NexaType.OBJECT;}return resolve(t);}if(e instanceof Field f){NexaType t=resolve(expr(f.target()));if(t instanceof NexaType.ObjectType o){NexaType x=o.fields().get(f.name());if(x==null)err("Unknown field '"+f.name()+"'",f.span());return x==null?NexaType.OBJECT:resolve(x);}err("Field access requires OBJECT/struct",f.span());return NexaType.OBJECT;}if(e instanceof Index i){NexaType t=resolve(expr(i.target()));NexaType idx=expr(i.index());if(t instanceof NexaType.Array a){requireAssignable(NexaType.INT64,idx,i.index().span(),"array index");return a.element();}if(NexaType.same(t,NexaType.OBJECT)){return NexaType.OBJECT;}err("Indexing requires ARRAY or OBJECT",i.span());return NexaType.OBJECT;}if(e instanceof Array a){NexaType et=null;for(Expr x:a.values()){NexaType xt=expr(x);if(et==null)et=xt;else et=common(et,xt,a.span());}return new NexaType.Array(et==null?NexaType.OBJECT:et);}if(e instanceof ObjectLit o){Map<String,NexaType>f=new LinkedHashMap<>();for(var x:o.fields().entrySet())f.put(x.getKey(),expr(x.getValue()));return new NexaType.ObjectType(f);}if(e instanceof Unary u){NexaType t=expr(u.expr());if(u.op().equals("!")){requireAssignable(NexaType.BOOLEAN,t,u.span(),"logical negation");return NexaType.BOOLEAN;}if(!NexaType.numeric(t))err("Unary numeric operator requires numeric value",u.span());return t;}if(e instanceof Binary b){NexaType l=expr(b.left()),r=expr(b.right());if(List.of("&&","||").contains(b.op())){requireAssignable(NexaType.BOOLEAN,l,b.left().span(),"logical operand");requireAssignable(NexaType.BOOLEAN,r,b.right().span(),"logical operand");return NexaType.BOOLEAN;}if(List.of("==","!=","<","<=",">",">=").contains(b.op())){if(!compatible(l,r))err("Incompatible comparison types: "+l.displayName()+" and "+r.displayName(),b.span());return NexaType.BOOLEAN;}if(!NexaType.numeric(l)||!NexaType.numeric(r))err("Arithmetic requires numeric operands",b.span());return common(l,r,b.span());}if(e instanceof Call c){for(Expr a:c.args())expr(a);return NexaType.OBJECT;}throw new IllegalStateException();}
    private NexaType common(NexaType a,NexaType b,SourceSpan s){if(NexaType.same(a,b))return a;if(NexaType.numeric(a)&&NexaType.numeric(b)){if(a.displayName().startsWith("FLOAT")||b.displayName().startsWith("FLOAT"))return NexaType.FLOAT64;if(a.displayName().contains("64")||b.displayName().contains("64"))return NexaType.INT64;return NexaType.INT32;}err("No safe implicit conversion from "+b.displayName()+" to "+a.displayName(),s);return a;}
    private boolean compatible(NexaType a,NexaType b){return NexaType.same(a,b)||(NexaType.numeric(a)&&NexaType.numeric(b));}
    private void requireAssignable(NexaType target,NexaType value,SourceSpan s,String where){target=resolve(target);value=resolve(value);if(NexaType.same(target,value))return;if(NexaType.numeric(target)&&NexaType.numeric(value)&&rank(value)<=rank(target)&&!(value.displayName().startsWith("FLOAT")&&!target.displayName().startsWith("FLOAT")))return;err("Type mismatch in "+where+": expected "+target.displayName()+", got "+value.displayName(),s);}
    private int rank(NexaType t){return switch(t.displayName()){case "INT8","UINT8"->1;case "INT16","UINT16"->2;case "INT32","UINT32"->3;case "INT64","UINT64"->4;case "FLOAT32"->5;case "FLOAT64"->6;default->0;};}
    private NexaType resolve(NexaType t){if(t instanceof NexaType.Named n){NexaType r=types.get(n.name());if(r==null){err("Unknown type: "+n.name(),new SourceSpan(0,0));return NexaType.OBJECT;}return r;}if(t instanceof NexaType.Array a)return new NexaType.Array(resolve(a.element()));return t;}
    private boolean isLValue(Expr e){return e instanceof Var||e instanceof Field||e instanceof Index;}
    private void define(String n,NexaType t){scopes.peek().put(n,t);}private NexaType lookup(String n){for(var s:scopes)if(s.containsKey(n))return s.get(n);return null;}private void err(String m,SourceSpan s){errors.add(new Diagnostic(m,s));}
}
