/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.0/userguide/multi_project_builds.html to learn more about multi-project builds.
 */

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "nexa-framework"
include("nexa-api")
include("nexa-core")
include("nexa-script-engine")
include("nexa-workspace-compiler")
include("nexa-cli")
include("nexa-mqtt-plugin")
include("nexa-control-plugin")
include("nexa-modbus-plugin")
include("nexa-asset-manager")
