/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 */

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "nexa-framework"
include("nexa-api")
include("nexa-core")
include("nexa-script-engine")
include("nexa-compiler")
include("nexa-cli")
include("nexa-mqtt-plugin")
include("nexa-control-plugin")
