/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects are included in the build.
 */

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "nexa-framework"
include("nexa-api")
include("nexa-tags")
include("nexa-core")
include("nexa-compiler")
include("nexa-cli")
